spring:
  r2dbc:
    url: r2dbc:oracle://localhost:1521/xe
    username: yourUsername
    password: yourPassword
  logging:
    level:
      root: INFO
      com.example.demo: DEBUG
      logging.level.org.springframework=DEBUG
      logging.level.org.springframework.web=DEBUG
      logging.level.org.springframework.r2dbc=DEBUG
 	org.springframework.r2dbc.core: DEBUG
    io.r2dbc.spi: DEBUG
com.zaxxer.hikari: DEBUG 	
level.io.r2dbc.pool=DEBUG
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
datasource:
    hikari:
      metrics:
        enabled: true
      pool-name: myPool
      maximum-pool-size: 20


